services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.GPU
    network_mode: host
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              count: 1
